"""initial schema

Revision ID: 56858ed87d50
Revises:
Create Date: 2026-09-01 18:12:49.282751
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '56858ed87d50'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('token_prefix', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packages_name'), 'packages', ['name'], unique=True)
    op.create_index(op.f('ix_packages_token_hash'), 'packages', ['token_hash'], unique=True)
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('allow_empty_override', sa.Boolean(), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('last_sync_status', sa.String(length=16), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_name'), 'sources', ['name'], unique=True)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('admin_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_value', sa.String(length=255), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_logs_action'), 'admin_logs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_logs_admin_user_id'), 'admin_logs', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_logs_created_at'), 'admin_logs', ['created_at'], unique=False)
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_name', sa.String(length=128), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('server', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('cipher', sa.String(length=64), nullable=True),
    sa.Column('network', sa.String(length=32), nullable=True),
    sa.Column('security', sa.String(length=32), nullable=True),
    sa.Column('tls', sa.Boolean(), nullable=True),
    sa.Column('sni', sa.String(length=255), nullable=True),
    sa.Column('fingerprint', sa.String(length=128), nullable=True),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('short_id', sa.String(length=64), nullable=True),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('host', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('node_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_country'), 'nodes', ['country'], unique=False)
    op.create_index(op.f('ix_nodes_enabled'), 'nodes', ['enabled'], unique=False)
    op.create_index(op.f('ix_nodes_name'), 'nodes', ['name'], unique=False)
    op.create_index(op.f('ix_nodes_node_fingerprint'), 'nodes', ['node_fingerprint'], unique=True)
    op.create_index(op.f('ix_nodes_source_id'), 'nodes', ['source_id'], unique=False)
    op.create_index(op.f('ix_nodes_source_name'), 'nodes', ['source_name'], unique=False)
    op.create_index(op.f('ix_nodes_type'), 'nodes', ['type'], unique=False)
    op.create_table('package_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('source_filter', sa.JSON(), nullable=True),
    sa.Column('country_filter', sa.JSON(), nullable=True),
    sa.Column('type_filter', sa.JSON(), nullable=True),
    sa.Column('include_keywords', sa.JSON(), nullable=True),
    sa.Column('exclude_keywords', sa.JSON(), nullable=True),
    sa.Column('rename_rules', sa.JSON(), nullable=True),
    sa.Column('sort_rules', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_package_rules_package_id'), 'package_rules', ['package_id'], unique=True)
    op.create_table('subscription_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_logs_created_at'), 'subscription_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_subscription_logs_package_id'), 'subscription_logs', ['package_id'], unique=False)
    op.create_index(op.f('ix_subscription_logs_status'), 'subscription_logs', ['status'], unique=False)
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('node_count', sa.Integer(), nullable=False),
    sa.Column('added_count', sa.Integer(), nullable=False),
    sa.Column('removed_count', sa.Integer(), nullable=False),
    sa.Column('changed_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_logs_created_at'), 'sync_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_sync_logs_source_id'), 'sync_logs', ['source_id'], unique=False)
    op.create_index(op.f('ix_sync_logs_status'), 'sync_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_logs_status'), table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_source_id'), table_name='sync_logs')
    op.drop_index(op.f('ix_sync_logs_created_at'), table_name='sync_logs')
    op.drop_table('sync_logs')
    op.drop_index(op.f('ix_subscription_logs_status'), table_name='subscription_logs')
    op.drop_index(op.f('ix_subscription_logs_package_id'), table_name='subscription_logs')
    op.drop_index(op.f('ix_subscription_logs_created_at'), table_name='subscription_logs')
    op.drop_table('subscription_logs')
    op.drop_index(op.f('ix_package_rules_package_id'), table_name='package_rules')
    op.drop_table('package_rules')
    op.drop_index(op.f('ix_nodes_type'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_source_name'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_source_id'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_node_fingerprint'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_name'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_enabled'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_country'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_index(op.f('ix_admin_logs_created_at'), table_name='admin_logs')
    op.drop_index(op.f('ix_admin_logs_admin_user_id'), table_name='admin_logs')
    op.drop_index(op.f('ix_admin_logs_action'), table_name='admin_logs')
    op.drop_table('admin_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_sources_name'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_packages_token_hash'), table_name='packages')
    op.drop_index(op.f('ix_packages_name'), table_name='packages')
    op.drop_table('packages')
    # ### end Alembic commands ###
